# Site settings
theme: jekyll-theme-cayman
title: Andrea was here
email: andij.cr@gmail.com
description: "Hic sunt leones. But mustly sketches and ideas."
baseurl: ""
url: "http://andijcr.github.io"
github_username: andijcr

# Build settings
permalink: pretty
