baseURL = 'http://andijcr.github.io/'
languageCode = 'en-us'
title = 'a site for stuff'
theme = 'cactus'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
description = 'Andrea was here'
mainSection = 'posts'
shwAllPostsOnHomePage = true

[[params.social]]
name = 'github'
link = 'https://github.com/andijcr'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Posts'
url = '/posts'
weight = 2

